swiftmailer:
    transport: smtp
    username: webmestre2@olymphys.fr
    password: Pi=3,1415
    host: mail.olymphys.fr
    port: 465
    encryption: ssl
    auth-mode: login
    timeout: 120
    spool: { type: 'memory' }
