twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig','bootstrap_4_horizontal_layout.html.twig']

    globals: 
         type_fichier : ['memoires','annexes','resumes','presentations','fichessecur']
         type_fichier_lit : ['mémoire','annexe','résume','présentation','fiche securité']