vich_uploader:
    db_driver: orm
    
    mappings:
        memoiresinter:
            uri_prefix: '%app.path.memoires_inter%'
            upload_destination: '%app.path.memoires_inter%'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer: 
                service: vich_uploader.namer_property
                options: { property: 'personalNamer'}       
        
        memoires:
            uri_prefix: '%app.path.memoires_nat%'
            upload_destination: '%app.path.memoires_nat%'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer: 
                service: vich_uploader.namer_property
                options: { property: 'personalNamer'}
                
         
        fichessecur:
            uri_prefix: '%app.path.fichessecur%'
            upload_destination: '%app.path.fichessecur%'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer: 
                service: vich_uploader.namer_property
                options: { property: 'personalNamer'}
                
                
        photosinter :
            uri_prefix: '%app.path.photosinter%'
            upload_destination: '%app.path.photosinter%'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer: 
                service: vich_uploader.namer_property
                options: { property: 'personalNamer'}
                
        photosinterthumb :
            uri_prefix: '%app.path.photosinterthumb%'
            upload_destination: '%app.path.photosinterthumb%'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer: 
                service: vich_uploader.namer_property
                options: { property: 'personalNamer'}
                
        resumes : 
            uri_prefix: '%app.path.resumes%'
            upload_destination: '%app.path.resumes%' 
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer: 
                service: vich_uploader.namer_property
                options: { property: 'personalNamer'}
        photoscn :
            uri_prefix: '%app.path.photosnat%'
            upload_destination: '%app.path.photosnat%'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer: 
                service: vich_uploader.namer_property
                options: { property: 'personalNamer'}
                
        photoscnthumb :
            uri_prefix: '%app.path.photosnatthumb%'
            upload_destination: '%app.path.photosnatthumb%'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer: 
                service: vich_uploader.namer_property
                options: { property: 'personalNamer'}
                
        presentation :
            uri_prefix: '%app.path.presentation%'
            upload_destination: '%app.path.presentation%'
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            namer: 
                service: vich_uploader.namer_property
                options: { property: 'personalNamer'}