<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ElevesinterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below. cope coller
 */
class ElevesinterRepository extends \Doctrine\ORM\EntityRepository
{

}
