<?php
namespace App\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use App\Entity\Equipesadmin;
use App\Entity\Fichiersequipes;

/**
 * 
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichiersequipesRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
                    {
                        parent::__construct($registry, Fichiersequipes::class);
                    }
    
    
    
public function getEquipesNatSansMemoire(FichiersequipesRepository $er): QueryBuilder
                {  //A reprendre ne donne pas le bon résultat	
                      return $qb1= $er ->createQueryBuilder('f')->select('f')
                                  ->Join('f.equipe','e')
                                  ->where('e.selectionnee  =:selectionnee')
                                  ->setParameter('selectionnee',TRUE)
                                  ->andWhere('f.typefichier =:memoire')
                                 ->setParameter('memoire',NULL)
                                  ->orWhere('f.typefichier>:type')
                                  ->setParameter('type',1)
                                  ->orderBy('e.lettre','ASC');
                 
                }
}