<?php
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

namespace App\Repository;

/**
 * FichessecurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichessecurRepository extends \Doctrine\ORM\EntityRepository
{
}