<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use App\Entity\Memoires;

/**
 * MemoiresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below. Copier coller de visites 
 */
class MemoiresRepository extends ServiceEntityRepository
{
     public function __construct(ManagerRegistry $registry)
                    {
                        parent::__construct($registry, Memoires::class);
                    }
     public function getMemoire(MemoiresRepository $mr): QueryBuilder
                {   
		
                    return $mr ->createQueryBuilder('m')->select('m');
                          //->where('e.lettre = :lettre')
                          //->setParameter('lettre',$lettre);    
                }
     /**
     * @param $equipe
     * @return Memoires[]
     */
    public function getMemoires($equipe): array
    {
        // automatically knows to select Products
        // the "p" is an alias you'll use in the rest of the query
        $qb = $this->createQueryBuilder('m')
            ->andWhere('m.equipe = :equipe')
            ->setParameter('equipe', $equipe)
            ->getQuery();

        return $qb->execute();

    }
   
}

