<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use App\Entity\Memoiresinter;

/**
 * MemoiresinterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below. Copier coller de visites 
 */
class MemoiresinterRepository extends ServiceEntityRepository
{
     public function __construct(ManagerRegistry $registry)
                    {
                        parent::__construct($registry, Memoiresinter::class);
                    }
/**
     * @param $equipe
     * @return Memoires[]
     */
    public function getMemoires($equipe): array
    {
        // automatically knows to select Products
        // the "p" is an alias you'll use in the rest of the query
        $qb = $this->createQueryBuilder('m')
            ->Where('m.equipe = :equipe')
            ->setParameter('equipe', $equipe)
            ->getQuery();

        return $qb->execute();

        // to get just one result:
        // $product = $qb->setMaxResults(1)->getOneOrNullResult();
    }
   public function getEquipeIntermemoiresless(MemoiresinterRepository $m): QueryBuilder
                {   
                }
                 
    
    
}

