<?php

namespace App\Repository;
use Doctrine\ORM\QueryBuilder;


/**
 * VisitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitesRepository extends \Doctrine\ORM\EntityRepository
{
    public static function getVisites(VisitesRepository $vr): QueryBuilder
                {   
		
                    return $vr->createQueryBuilder('v')->select('v');
                           // ->where('v.attribue = :attribue')
                           // ->setParameter('attribue',0);    
                    
 
                     }
    
    
    
}
