easy_admin :
    design:
                brand_color: '#FF0000'
                assets:
                    css:
                        # ...
                        - 'css/admin.css'
                menu:
                    - { entity: 'Adminsite' , permission: 'ROLE_SUPER_ADMIN', icon : 'cogs'}
                    - { entity: 'User', label : 'Utilisateurs', permission: 'ROLE_SUPER_ADMIN', icon : 'user' }
                    - { entity: 'Jures' , permission: 'ROLE_SUPER_ADMIN', icon : 'graduation-cap'}
                    - label : 'Concours interacadémique'
                      icon : 
                      css_class: 'text-bold'
                      children :
                         - { entity : 'Centrescia', 'label' : 'Centres interacadémiques', icon : 'city'}
                         - { entity : 'Equipesadmin', 'label' : 'Equipes des cia', icon : 'user-friends'}
                         - { entity : 'Fichiersequipesmemoiresinter', 'label' : 'Les mémoires' , icon : 'book'}
                         - { entity : 'Fichiersequipesresumes', 'label' : 'Les résumés' , icon : 'book'}
                         - { entity : 'Fichiersequipesfichessecur', 'label' : 'Les fiches sécurités' , icon : 'book'}
                         - { entity : 'Elevesinter', 'label' : 'Elèves inscrits', icon : 'child' }
                         - { entity : 'Photosinter', 'label' : ' Lesphotos', icon : 'images'}
                         
                    - label : 'Concours national'
                      icon : ''
                      children :
                        - label: 'Equipes'
                        - { label : 'Palmares des équipes', entity: 'Equipes' , icon : 'asterisk'}
                        - { label : 'Administration des équipes' , entity : 'Selectionnees', icon : 'user-friends'}
                        - { entity : 'Fichiersequipesmemoires', 'label' : 'Les mémoires' , icon : 'book'}
                        - { entity : 'Fichiersequipesresumes', 'label' : 'Les résumés' , icon : 'book'}
                        - { entity : 'Fichiersequipespresentations', 'label' : 'Les présentations' , icon : 'book'}
                        - { entity: 'Eleves' , icon : 'asterisk'}
                        - { label : 'Les photos', entity: 'Photoscn' , icon : 'images'}
                        - label : 'Les recompenses'
                        - { entity:  'Classement' , icon : 'asterisk'}
                        - { entity:  'Prix' , icon : 'asterisk'}
                        - { entity: 'Visites' , icon : 'asterisk'}
                        - { entity: 'Cadeaux' , icon : 'asterisk'}
                        
                    - { label: 'Retour à la page d''accueil', route: 'core_home' , icon : 'home'}
                    - { label : 'Deconnexion' , route: 'logout', icon : 'door-open'}
                   #- {  label: 'Retour à la page d''accueil', url: '/public/index.php' , icon : 'home'}
                   # - { label : 'Deconnexion' , url : '/public/index.php/logout', icon : 'door-open'
                form_theme:
                - '@EasyAdmin/form/bootstrap_4.html.twig'
                - '@VichUploader/Form/fields.html.twig'    
